[project]
name = "ctd-rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "moviepy>=2.2.1",
    "openai>=1.90.0",
    "pydub>=0.25.1",
]
